# Generated by Django 6.0.4 on 2026-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentaAPP', '0002_alter_libromayor_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('wallet_usuario', 'Wallet de Usuario'), ('casa', 'Cuenta de la Casa'), ('apuestas_pendientes', 'Apuestas Pendientes'), ('bonos', 'Bonos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='monto',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
