# Generated by Django 6.0.4 on 2026-05-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('hash_anterior', models.CharField(max_length=64)),
                ('hash_actual', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
