# Generated by Django 6.0.4 on 2026-05-28 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPP', '0004_juegoresponsabe_ultima_modificacion_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni_digito_verificador',
            field=models.CharField(default='', max_length=1, validators=[django.core.validators.RegexValidator(message='El digito verificador debe ser un numero del 0 al 9.', regex='^\\d$')], verbose_name='digito verificador DNI'),
        ),
    ]
