# Generated by Django 6.0.4 on 2026-05-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='deporte',
            field=models.CharField(choices=[('futbol', 'Futbol'), ('baloncesto', 'Baloncesto'), ('voleibol', 'Voleibol'), ('tenis', 'Tenis')], default='futbol', max_length=20),
        ),
        migrations.AddField(
            model_name='mercado',
            name='suspension_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mercado',
            name='tipo',
            field=models.CharField(choices=[('resultado_final', 'Resultado Final (1X2)'), ('ganador_partido', 'Ganador del Partido (1-2)'), ('ganador_sets', 'Marcador Exacto de Sets')], default='resultado_final', max_length=30),
        ),
        migrations.AlterField(
            model_name='seleccion',
            name='tipo',
            field=models.CharField(choices=[('1', 'Gana local'), ('X', 'Empate'), ('2', 'Gana visitante'), ('3-0', '3-0'), ('3-1', '3-1'), ('3-2', '3-2'), ('2-3', '2-3'), ('1-3', '1-3'), ('0-3', '0-3')], max_length=3),
        ),
    ]
