# Generated by Django 6.0.4 on 2026-05-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestaAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuestamaestra',
            name='estado',
            field=models.CharField(choices=[('accepted', 'Aceptada'), ('won', 'Ganada'), ('loast', 'Perdida'), ('cashed_out', 'Cerrada Anticipadamente'), ('void', 'Anulada')], default='accepted', max_length=20),
        ),
    ]
